var pN=[],oN={},iN={},opN={},cN={},bN={},imN={},swN={},rN={},rcN={},_='left,right,middle',__='top,middle,bottom',R=/^\d+$/,B=function(k,v,s){v&&s.indexOf(v)<0&&e.push(k+' 必须是 '+s)},C=function(k){g[k]&&!H(g[k])&&e.push(k+' 颜色无效')},N=function(k,v){v&&(!R.test(v)||+v<0||+v>100)&&e.push(k+' 必须是0-100的数字')},T=function(k){var v=g[k];v&&v!=='true'&&v!=='false'&&e.push(k+' 必须是true/false')};
C('page.background.color');T('page.background.image.cut');C('page.modal.color');C('page.btn.color');
['page.modal.transparency','page.modal.blur','page.btn.transparency','page.btn.blur'].forEach(function(k){N(k,g[k])});
B('page.content.align',g['page.content.align'],_);B('page.animation.type',g['page.animation.type'],'slide,fade,rotate,zoomin,zoomout,none');
g['page.content.style']&&g['page.content.style'].split('\\').forEach(function(s){s&&'quote,title,bold,tilt,underline,url,delete'.indexOf(s)<0&&e.push('page.content.style 无效样式 '+s)});
B('page.content.distance',g['page.content.distance'],'none,min,1,2,3,max');
g['page.animation.duration']&&!R.test(g['page.animation.duration'])&&e.push('page.animation.duration 必须是数字');
N('page.image.size',g['page.image.size']);T('page.image.cut');
Object.keys(g).forEach(function(k){var m,x,y,z,K;
if(m=k.match(/^page\.(\d+)\./)){x=+m[1];x<1&&e.push('page.'+x+' x<1');pN.indexOf(x)<0&&pN.push(x);/\.(background|modal|btn)\.color$/.test(k)&&C(k);/^page\.\d+\.content\.align$/.test(k)&&B(k,g[k],_);/^page\.\d+\.content\.style$/.test(k)&&g[k]&&g[k].split('\\').forEach(function(s){s&&'quote,title,bold,tilt,underline,url,delete'.indexOf(s)<0&&e.push(k+' 无效样式 '+s)});/^page\.\d+\.content\.distance$/.test(k)&&B(k,g[k],'none,min,1,2,3,max');/^page\.\d+\.animation\.type$/.test(k)&&B(k,g[k],'slide,fade,rotate,zoomin,zoomout,none');/^page\.\d+\.animation\.duration$/.test(k)&&g[k]&&!R.test(g[k])&&e.push(k+' 必须是数字');/^page\.\d+\.image\.size$/.test(k)&&N(k,g[k]);/^page\.\d+\.image\.cut$/.test(k)&&T(k);/^page\.\d+\.(modal|btn)\.(transparency|blur)$/.test(k)&&N(k,g[k])}
if(m=k.match(/^page\.(\d+)\.content\.(\d+)(\..*)?$/)){x=+m[1];y=+m[2];y<1&&e.push(k+' y<1');(cN[x]=cN[x]||[]).indexOf(y)<0&&cN[x].push(y);m[3]==='.align'&&B(k,g[k],_);m[3]==='.style'&&g[k]&&g[k].split('\\').forEach(function(s){s&&'quote,title,bold,tilt,underline,url,delete'.indexOf(s)<0&&e.push(k+' 无效样式 '+s)});m[3]==='.distance'&&B(k,g[k],'none,min,1,2,3,max')}
if(m=k.match(/^page\.(\d+)\.options\.(\d+)\./)){x=+m[1];y=+m[2];y<1&&e.push(k+' y<1');(oN[x]=oN[x]||[]).indexOf(y)<0&&oN[x].push(y)}
if(m=k.match(/^page\.(\d+)\.options\.(\d+)\.option\.(\d+)$/)){x=+m[1];y=+m[2];z=+m[3];z<1&&e.push(k+' z<1');K=x+'.'+y;(opN[K]=opN[K]||[]).indexOf(z)<0&&opN[K].push(z)}
if(m=k.match(/^page\.(\d+)\.input\.(\d+)\./)){x=+m[1];y=+m[2];y<1&&e.push(k+' y<1');(iN[x]=iN[x]||[]).indexOf(y)<0&&iN[x].push(y)}
if(m=k.match(/^page\.(\d+)\.btn\.(\d+)\./)){x=+m[1];y=+m[2];y<1&&e.push(k+' y<1');(bN[x]=bN[x]||[]).indexOf(y)<0&&bN[x].push(y)}
if(m=k.match(/^page\.(\d+)\.image\.(\d+)\./)){x=+m[1];y=+m[2];y<1&&e.push(k+' y<1');(imN[x]=imN[x]||[]).indexOf(y)<0&&imN[x].push(y)}
if(m=k.match(/^page\.(\d+)\.image\.(\d+)\.switch\.(\d+)$/)){x=+m[1];y=+m[2];z=+m[3];z<1&&e.push(k+' z<1');K=x+'.'+y;(swN[K]=swN[K]||[]).indexOf(z)<0&&swN[K].push(z)}
if(m=k.match(/^page\.(\d+)\.row\.(\d+)\./)){x=+m[1];y=+m[2];y<1&&e.push(k+' y<1');(rN[x]=rN[x]||[]).indexOf(y)<0&&rN[x].push(y)}
if(m=k.match(/^page\.(\d+)\.row\.(\d+)\.(\d+)\./)){x=+m[1];y=+m[2];z=+m[3];z<1&&e.push(k+' z<1');K=x+'.'+y;(rcN[K]=rcN[K]||[]).indexOf(z)<0&&rcN[K].push(z)}
/^page\.\d+\.btn\.\d+\.align$/.test(k)&&B(k,g[k],_)});
pN.forEach(function(x){var P,Q,K,v;
oN[x]&&oN[x].forEach(function(y){P='page.'+x+'.options.'+y;g[P+'.title']||e.push('缺少 '+P+'.title');g[P+'.key']||e.push('缺少 '+P+'.key');v=+(g[P+'.default']||1);K=x+'.'+y;(!opN[K]||opN[K].indexOf(v)<0)&&e.push(P+'.default 指向不存在的option.'+v)});
iN[x]&&iN[x].forEach(function(y){P='page.'+x+'.input.'+y;g[P+'.title']||e.push('缺少 '+P+'.title');g[P+'.key']||e.push('缺少 '+P+'.key')});
cN[x]&&cN[x].forEach(function(y){P='page.'+x+'.content.'+y;v=g[P+'.style']||'';v.indexOf('url')>=0&&((v=g[P+'.url']||'')?(v.indexOf('http://')&&v.indexOf('https://'))&&e.push(P+'.url 必须是http/https链接'):e.push('缺少 '+P+'.url'));(v=g[P+'.enter'])&&v!=='true'&&v!=='false'&&e.push(P+'.enter 必须是true/false');C(P+'.color.text');C(P+'.color.background')});
bN[x]&&bN[x].forEach(function(y){P='page.'+x+'.btn.'+y;g[P+'.content']||e.push('缺少 '+P+'.content');C(P+'.color');(v=g[P+'.mode'])&&'redirect,cover'.indexOf(v)<0&&e.push(P+'.mode 必须是redirect/cover');T(P+'.reclickable');T(P+'.killer');(v=g[P+'.death.type'])&&'remove,disable'.indexOf(v)<0&&e.push(P+'.death.type 必须是remove/disable');B(P+'.animation.type',g[P+'.animation.type'],'slide,fade,rotate,zoomin,zoomout,none');g[P+'.animation.duration']&&!R.test(g[P+'.animation.duration'])&&e.push(P+'.animation.duration 必须是数字');(v=g[P+'.page'])&&pN.indexOf(+v)<0&&e.push(P+'.page 指向不存在的page.'+v)});
imN[x]&&imN[x].forEach(function(y){P='page.'+x+'.image.'+y;g[P+'.url']||e.push('缺少 '+P+'.url');B(P+'.align',g[P+'.align'],_);(v=g[P+'.click.type'])&&'disable,modal,switch,detail'.indexOf(v)<0&&e.push(P+'.click.type 必须是disable/modal/switch/detail');N(P+'.size',g[P+'.size']);T(P+'.cut');v==='modal'&&((v=g[P+'.modal.modal'])&&pN.indexOf(+v)<0&&e.push(P+'.modal.modal 指向不存在的page.'+v),(v=g[P+'.modal.mode'])&&'redirect,cover'.indexOf(v)<0&&e.push(P+'.modal.mode 必须是redirect/cover'),B(P+'.modal.animation.type',g[P+'.modal.animation.type'],'slide,fade,rotate,zoomin,zoomout,none'),g[P+'.modal.animation.duration']&&!R.test(g[P+'.modal.animation.duration'])&&e.push(P+'.modal.animation.duration 必须是数字'));g[P+'.click.type']==='switch'&&T(P+'.switch.cycle')});
rN[x]&&rN[x].forEach(function(y){P='page.'+x+'.row.'+y;(v=g[P+'.ratio'])&&!/^\d+(:\d+)*$/.test(v)&&e.push(P+'.ratio 格式错误');K=x+'.'+y;rcN[K]&&rcN[K].forEach(function(z){Q=P+'.'+z;B(Q+'.type',g[Q+'.type'],'content,btn,image');B(Q+'.align',g[Q+'.align'],_);B(Q+'.valign',g[Q+'.valign'],__);v=g[Q+'.type']||'content';v==='btn'&&(C(Q+'.btn.color'),(v=g[Q+'.btn.mode'])&&'redirect,cover'.indexOf(v)<0&&e.push(Q+'.btn.mode 必须是redirect/cover'),T(Q+'.btn.reclickable'),T(Q+'.btn.killer'),(v=g[Q+'.btn.death.type'])&&'remove,disable'.indexOf(v)<0&&e.push(Q+'.btn.death.type 必须是remove/disable'),B(Q+'.btn.animation.type',g[Q+'.btn.animation.type'],'slide,fade,rotate,zoomin,zoomout,none'),g[Q+'.btn.page']&&pN.indexOf(+g[Q+'.btn.page'])<0&&e.push(Q+'.btn.page 指向不存在的page'));(v=g[Q+'.type'])==='image'&&(B(Q+'.image.align',g[Q+'.image.align'],_),(v=g[Q+'.image.click.type'])&&'disable,modal,switch,detail'.indexOf(v)<0&&e.push(Q+'.image.click.type 必须是disable/modal/switch/detail'),N(Q+'.image.size',g[Q+'.image.size']),T(Q+'.image.cut'));(g[Q+'.type']||'content')==='content'&&(g[Q+'.content.style']&&g[Q+'.content.style'].split('\\').forEach(function(s){s&&'quote,title,bold,tilt,underline,url,delete'.indexOf(s)<0&&e.push(Q+'.content.style 无效样式 '+s)}),C(Q+'.content.color.text'),C(Q+'.content.color.background'))})});
(v=g['page.'+x+'.row.height'])&&!/^(\d+(,\d+)*)(:(\d+(,\d+)*))*$/.test(v)&&e.push('page.'+x+'.row.height 格式错误')});